# Generated by Django 3.2.3 on 2022-06-21 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FABRICANTE',
            fields=[
                ('id_fabricante', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_fabricante', models.CharField(max_length=50, verbose_name='Fabricante')),
            ],
        ),
        migrations.CreateModel(
            name='TIPO_PRODUCTO',
            fields=[
                ('id_tipo_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nom_tipo_producto', models.CharField(max_length=50, verbose_name='Nombre del tipo producto')),
            ],
        ),
        migrations.CreateModel(
            name='PRODUCTO',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, null=True, verbose_name='Nombre del producto')),
                ('precio', models.IntegerField(null=True, verbose_name='Precio del producto')),
                ('stock', models.IntegerField(null=True, verbose_name='Stock del producto')),
                ('desc', models.TextField(null=True, verbose_name='Descripcion del producto')),
                ('imagenProducto', models.ImageField(null=True, upload_to='fotoproductos', verbose_name='Imagen del producto')),
                ('nom_tipo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ENTELAPP.tipo_producto', verbose_name='Tipo producto')),
                ('nombre_fabricante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ENTELAPP.fabricante', verbose_name='Fabricante')),
            ],
        ),
    ]
