# Generated by Django 3.2.3 on 2022-06-07 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TIPO_PRODUCTO',
            fields=[
                ('id_tipo_producto', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID TIPO PRODUCTO')),
                ('nom_tipo_producto', models.CharField(max_length=50, verbose_name='Nombre del tipo producto')),
            ],
        ),
        migrations.CreateModel(
            name='PRODUCTO',
            fields=[
                ('id_producto', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID Producto')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del producto')),
                ('precio', models.IntegerField(verbose_name='Precio del producto')),
                ('stock', models.IntegerField(verbose_name='Stock del producto')),
                ('desc', models.IntegerField(verbose_name='Descripcion del producto')),
                ('fabricante', models.CharField(max_length=50, verbose_name='Fabricante del producto')),
                ('imagen', models.ImageField(upload_to='', verbose_name='Imagen del producto')),
                ('nom_tipo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ENTELAPP.tipo_producto', verbose_name='Tipo producto')),
            ],
        ),
    ]
