# Generated by Django 4.0.1 on 2022-06-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ENTELAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='desc',
            field=models.TextField(null=True, verbose_name='Descripcion del producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fabricante',
            field=models.CharField(max_length=50, null=True, verbose_name='Fabricante del producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='id_producto',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(null=True, upload_to='fotoproductos', verbose_name='Imagen del producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=50, null=True, verbose_name='Nombre del producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(null=True, verbose_name='Precio del producto'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(null=True, verbose_name='Stock del producto'),
        ),
        migrations.AlterField(
            model_name='tipo_producto',
            name='id_tipo_producto',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
