# Generated by Django 4.0.1 on 2022-06-15 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ENTELAPP', '0002_alter_producto_desc_alter_producto_fabricante_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='imagen',
            new_name='imagenProducto',
        ),
    ]
